### ISSUE TITLE
Check for cruft / deprecations in dependencies

### ISSUE THREAD

**Issue by oponder** [giantswarm/happa#124]
It's been a while since I've checked if Happa dependencies are up to date. It's best to do this occasionally, instead of having to try and align a lot of things at once later.

Puja already noticed while building:
- `npm WARN deprecated node-uuid@1.4.8: Use uuid module instead`

### TODO:

- [ ] `giantswarm-js-client`:
  - [ ] Replace `node-uuid` with `uuid`
  - [ ] Replace `js-data@2.3.0` with v3
- [ ] `happa`:
  - [ ] Replace `babel-preset-es2015` with `babel-preset-env`. See http://babeljs.io/env (https://github.com/giantswarm/happa/pull/272)

### Future

- Replace `grunt@1.0.1` with newer version, to resolve these issue:
   - deprecated coffee-script dependency
   - deprecated use of `http2@3.3.7` module
